### ISSUE TITLE
Nie można ustawić poczekalni

### ISSUE THREAD

**Issue by troley12** [games647/LogIt#1]
Pomimo tego, że mam uprawnienia nie mogę ustawić poczekalni, ani też newbie teleport.  Robię to komendami **/logit config set waitingRoom.location $** i **/logit config set newbieTeleport.location**. Po użyciu każdej z nich dostaję błąd, że nie mam dostępu do tej komendy. Wersja najnowsza. :)

**Comment by TuxCoding** [comment]
Please speak english.

**Comment by troley12** [comment]
Sorry, I thought you were from Polish :D. Despite the fact that I have the permissions I can not set waiting room or newbie teleport. I do it commands. **/logit config set waitingRoom.location $** and **/logit config set newbieTeleport.location**. After use, I get an error that does not amm access. I have the latest version. If I set the positions in this config is working properly.

**Comment by TuxCoding** [comment]
> After use, I get an error that does not amm access. I have the latest version. If I set the positions in this config is working properly.

Could you send me that error?

**Comment by TuxCoding** [comment]
You have to the permissions with a permissions plugin. OP permissions are not used for this.
