### ISSUE TITLE
Error on PlayerJoinEvent and on closing database connection

### ISSUE THREAD

**Issue by aorozcog** [games647/LogIt#2]
Hello 😄  Thanks for update this plugin. I was stucked on 1.8 because of this 😢 
On the version for 1.11, when a player joins to the server, the console shows this error:
http://pastebin.com/863E0qny

I believe that it is the message broadcasted to the user, because when I join to the server, the typical message ''please use /login'' is missing.

Also, when I closed the server I detected another error related to SQL databse: http://pastebin.com/PGsZ6jmT

Thanks for your time 👍

**Comment by TuxCoding** [comment]
>On the version for 1.11, when a player joins to the server, the console shows this error:
http://pastebin.com/863E0qny

It cannot find the of the waitingRoom file

**Comment by TuxCoding** [comment]
>Also, when I closed the server I detected another error related to SQL databse: http://pastebin.com/PGsZ6jmT

Do you invoked the stop command twice?

EDIT: the stop requests comes in twice:    
> at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:417)

**Comment by aorozcog** [comment]
About the PlayerJoinEvent it is fixed with the correct waiting room.
Now, about the error on stopping the server. I invoked stop just one time.

**Comment by TuxCoding** [comment]
What the time of the first exception?

**Comment by aorozcog** [comment]
The exception happens everytime that the server stops. I also let the plugin regenerate all the plugins files, but still happens

http://pastebin.com/kfhcdGdG
